### ISSUE TITLE
Infografia de hilos

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/infografia-de-hilos-NoeliaGlez#2]
[Infografía de hilos en consola en C#.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-NoeliaGlez/files/8867185/Infografia.de.hilos.en.consola.en.C.pdf)

**Comment by Litzy-lopez4** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
